#------------------------------------------------------------------------------
# Rules
#------------------------------------------------------------------------------
.PHONY: all clean

all: 
	make -C ../src superclean all target=armv7-android
	make -C ../test/example clean all target=armv7-android
clean:
	echo "no real clean here."
